/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SeoDevRouteImport } from './routes/seo-dev'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as ReservationsRouteImport } from './routes/reservations'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as ReservationsConfirmationReferenceCodeRouteImport } from './routes/reservations.confirmation.$referenceCode'

const SeoDevRoute = SeoDevRouteImport.update({
  id: '/seo-dev',
  path: '/seo-dev',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsRoute = ReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin/_layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsConfirmationReferenceCodeRoute =
  ReservationsConfirmationReferenceCodeRouteImport.update({
    id: '/confirmation/$referenceCode',
    path: '/confirmation/$referenceCode',
    getParentRoute: () => ReservationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/reservations': typeof ReservationsRouteWithChildren
  '/rooms': typeof RoomsRoute
  '/seo-dev': typeof SeoDevRoute
  '/admin': typeof AdminLayoutRoute
  '/admin/login': typeof AdminLoginRoute
  '/reservations/confirmation/$referenceCode': typeof ReservationsConfirmationReferenceCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/reservations': typeof ReservationsRouteWithChildren
  '/rooms': typeof RoomsRoute
  '/seo-dev': typeof SeoDevRoute
  '/admin': typeof AdminLayoutRoute
  '/admin/login': typeof AdminLoginRoute
  '/reservations/confirmation/$referenceCode': typeof ReservationsConfirmationReferenceCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/reservations': typeof ReservationsRouteWithChildren
  '/rooms': typeof RoomsRoute
  '/seo-dev': typeof SeoDevRoute
  '/admin/_layout': typeof AdminLayoutRoute
  '/admin/login': typeof AdminLoginRoute
  '/reservations/confirmation/$referenceCode': typeof ReservationsConfirmationReferenceCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/gallery'
    | '/reservations'
    | '/rooms'
    | '/seo-dev'
    | '/admin'
    | '/admin/login'
    | '/reservations/confirmation/$referenceCode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/gallery'
    | '/reservations'
    | '/rooms'
    | '/seo-dev'
    | '/admin'
    | '/admin/login'
    | '/reservations/confirmation/$referenceCode'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/gallery'
    | '/reservations'
    | '/rooms'
    | '/seo-dev'
    | '/admin/_layout'
    | '/admin/login'
    | '/reservations/confirmation/$referenceCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  ReservationsRoute: typeof ReservationsRouteWithChildren
  RoomsRoute: typeof RoomsRoute
  SeoDevRoute: typeof SeoDevRoute
  AdminLayoutRoute: typeof AdminLayoutRoute
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/seo-dev': {
      id: '/seo-dev'
      path: '/seo-dev'
      fullPath: '/seo-dev'
      preLoaderRoute: typeof SeoDevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations': {
      id: '/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof ReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations/confirmation/$referenceCode': {
      id: '/reservations/confirmation/$referenceCode'
      path: '/confirmation/$referenceCode'
      fullPath: '/reservations/confirmation/$referenceCode'
      preLoaderRoute: typeof ReservationsConfirmationReferenceCodeRouteImport
      parentRoute: typeof ReservationsRoute
    }
  }
}

interface ReservationsRouteChildren {
  ReservationsConfirmationReferenceCodeRoute: typeof ReservationsConfirmationReferenceCodeRoute
}

const ReservationsRouteChildren: ReservationsRouteChildren = {
  ReservationsConfirmationReferenceCodeRoute:
    ReservationsConfirmationReferenceCodeRoute,
}

const ReservationsRouteWithChildren = ReservationsRoute._addFileChildren(
  ReservationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  ReservationsRoute: ReservationsRouteWithChildren,
  RoomsRoute: RoomsRoute,
  SeoDevRoute: SeoDevRoute,
  AdminLayoutRoute: AdminLayoutRoute,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
